/********************************************************************
* TGVKellyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGVKellyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGVKellyDict();
extern void G__cpp_setup_inheritanceTGVKellyDict();
extern void G__cpp_setup_typetableTGVKellyDict();
extern void G__cpp_setup_memvarTGVKellyDict();
extern void G__cpp_setup_globalTGVKellyDict();
extern void G__cpp_setup_memfuncTGVKellyDict();
extern void G__cpp_setup_funcTGVKellyDict();
extern void G__set_cpp_environmentTGVKellyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGVKelly.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGVKellyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGVKellyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGVKellyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGVKellyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGVKellyDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGVKellyDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGVKellyDictLN_TLorentzVector;
extern G__linked_taginfo G__TGVKellyDictLN_TGVKelly;

/* STUB derived class for protected member access */
