/********************************************************************
* TGenBaseDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenBaseDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenBaseDict();
extern void G__cpp_setup_inheritanceTGenBaseDict();
extern void G__cpp_setup_typetableTGenBaseDict();
extern void G__cpp_setup_memvarTGenBaseDict();
extern void G__cpp_setup_globalTGenBaseDict();
extern void G__cpp_setup_memfuncTGenBaseDict();
extern void G__cpp_setup_funcTGenBaseDict();
extern void G__set_cpp_environmentTGenBaseDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenBase.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenBaseDictLN_TClass;
extern G__linked_taginfo G__TGenBaseDictLN_TBuffer;
extern G__linked_taginfo G__TGenBaseDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenBaseDictLN_TObject;
extern G__linked_taginfo G__TGenBaseDictLN_TString;
extern G__linked_taginfo G__TGenBaseDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__TGenBaseDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenBaseDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenBaseDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenBaseDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenBaseDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenBaseDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenBaseDictLN_TVector3;
extern G__linked_taginfo G__TGenBaseDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenBaseDictLN_TGenGeo;
extern G__linked_taginfo G__TGenBaseDictLN_TGenSoLIDGeo;
extern G__linked_taginfo G__TGenBaseDictLN_TRandom2;
extern G__linked_taginfo G__TGenBaseDictLN_TGenBase;

/* STUB derived class for protected member access */
