/********************************************************************
* TGenSoLIDGeoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenSoLIDGeoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenSoLIDGeoDict();
extern void G__cpp_setup_inheritanceTGenSoLIDGeoDict();
extern void G__cpp_setup_typetableTGenSoLIDGeoDict();
extern void G__cpp_setup_memvarTGenSoLIDGeoDict();
extern void G__cpp_setup_globalTGenSoLIDGeoDict();
extern void G__cpp_setup_memfuncTGenSoLIDGeoDict();
extern void G__cpp_setup_funcTGenSoLIDGeoDict();
extern void G__set_cpp_environmentTGenSoLIDGeoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenSoLIDGeo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TClass;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TBuffer;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TObject;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TGenGeo;
extern G__linked_taginfo G__TGenSoLIDGeoDictLN_TGenSoLIDGeo;

/* STUB derived class for protected member access */
