/********************************************************************
* TGenGeoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenGeoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenGeoDict();
extern void G__cpp_setup_inheritanceTGenGeoDict();
extern void G__cpp_setup_typetableTGenGeoDict();
extern void G__cpp_setup_memvarTGenGeoDict();
extern void G__cpp_setup_globalTGenGeoDict();
extern void G__cpp_setup_memfuncTGenGeoDict();
extern void G__cpp_setup_funcTGenGeoDict();
extern void G__set_cpp_environmentTGenGeoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenGeo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenGeoDictLN_TClass;
extern G__linked_taginfo G__TGenGeoDictLN_TBuffer;
extern G__linked_taginfo G__TGenGeoDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenGeoDictLN_TObject;
extern G__linked_taginfo G__TGenGeoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenGeoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenGeoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenGeoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenGeoDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenGeoDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenGeoDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenGeoDictLN_TGenGeo;

/* STUB derived class for protected member access */
