/********************************************************************
* TGenSoLIDDVCSDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGenSoLIDDVCSDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGenSoLIDDVCSDict();
extern void G__cpp_setup_inheritanceTGenSoLIDDVCSDict();
extern void G__cpp_setup_typetableTGenSoLIDDVCSDict();
extern void G__cpp_setup_memvarTGenSoLIDDVCSDict();
extern void G__cpp_setup_globalTGenSoLIDDVCSDict();
extern void G__cpp_setup_memfuncTGenSoLIDDVCSDict();
extern void G__cpp_setup_funcTGenSoLIDDVCSDict();
extern void G__set_cpp_environmentTGenSoLIDDVCSDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGenSoLIDDVCS.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TClass;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TBuffer;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMemberInspector;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TObject;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TLorentzVector;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TGenGeo;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TGenSoLIDGeo;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TGenBase;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TGVKelly;
extern G__linked_taginfo G__TGenSoLIDDVCSDictLN_TGenSoLIDDVCS;

/* STUB derived class for protected member access */
